global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "url-shortener-api"
    static_configs:
      - targets: ["api:3030"]

  - job_name: "url-shortener-worker"
    static_configs:
      - targets: ["worker:2112"]

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]
